export const competitionsSeed = [
  {
    id: "challenger-2026",
    name: "Challenger 2026",
    status: "live",
    format: "Single Elimination",
    rule: "Best of 3",
    venue: "Hermanus Sports Club",
    dateStart: "2026-07-24",
    dateEnd: "2026-07-31",
    teams: 8,
    players: 14,
    matchesCompleted: 1,
    matchesTotal: 4,
    courts: 8,
    liveMatches: 4,
    waitingMatches: 2,
    spectators: 322,
    progress: 25,
    cover: "A",
    timing: "Live now",
  },
  {
    id: "schools-cup-2026",
    name: "Schools Cup 2026",
    status: "upcoming",
    format: "Group Stage + Knockout",
    rule: "Best of 3",
    venue: "Cape Town Padel Park",
    dateStart: "2026-08-07",
    dateEnd: "2026-08-09",
    teams: 12,
    players: 24,
    matchesCompleted: 0,
    matchesTotal: 24,
    courts: 6,
    liveMatches: 0,
    waitingMatches: 0,
    spectators: 0,
    progress: 8,
    cover: "B",
    timing: "Starts in 10 days",
  },
  {
    id: "club-championships",
    name: "Club Championships",
    status: "draft",
    format: "Double Elimination",
    rule: "Best of 3",
    venue: "Hermanus Sports Club",
    dateStart: "2026-08-21",
    dateEnd: "2026-08-23",
    teams: 16,
    players: 30,
    matchesCompleted: 0,
    matchesTotal: 0,
    courts: 10,
    liveMatches: 0,
    waitingMatches: 0,
    spectators: 0,
    progress: 62,
    cover: "C",
    timing: "Setup 62% complete",
  },
  {
    id: "winter-league",
    name: "Winter League",
    status: "scheduled",
    format: "Round Robin",
    rule: "Best of 3",
    venue: "Overberg Padel Centre",
    dateStart: "2026-09-30",
    dateEnd: "2026-11-14",
    teams: 24,
    players: 48,
    matchesCompleted: 0,
    matchesTotal: 72,
    courts: 12,
    liveMatches: 0,
    waitingMatches: 0,
    spectators: 0,
    progress: 15,
    cover: "D",
    timing: "Starts in 64 days",
  },
  {
    id: "autumn-open",
    name: "Autumn Open",
    status: "completed",
    format: "Single Elimination",
    rule: "Best of 3",
    venue: "Hermanus Sports Club",
    dateStart: "2026-04-12",
    dateEnd: "2026-04-14",
    teams: 16,
    players: 32,
    matchesCompleted: 31,
    matchesTotal: 31,
    courts: 8,
    liveMatches: 0,
    waitingMatches: 0,
    spectators: 864,
    progress: 100,
    cover: "E",
    timing: "Completed 14 April",
  },
  {
    id: "summer-series-2025",
    name: "Summer Series 2025",
    status: "archived",
    format: "Round Robin",
    rule: "Best of 3",
    venue: "Hermanus Sports Club",
    dateStart: "2025-12-02",
    dateEnd: "2025-12-20",
    teams: 20,
    players: 40,
    matchesCompleted: 50,
    matchesTotal: 50,
    courts: 8,
    liveMatches: 0,
    waitingMatches: 0,
    spectators: 1290,
    progress: 100,
    cover: "F",
    timing: "Archived",
  },
];

export const courts = [
  { id: 1, status: "live", teams: "E / L  vs  S / H", score: "30–15", meta: "57 minutes", action: "Open" },
  { id: 2, status: "live", teams: "G / N  vs  S / S", score: "40–30", meta: "63 minutes", action: "Open" },
  { id: 3, status: "waiting", teams: "L / J  vs  C / C", score: "Ready", meta: "Players checked in", action: "Start Match" },
  { id: 4, status: "delayed", teams: "J / L  vs  F / M", score: "Paused", meta: "Rain delay", action: "Update" },
  { id: 5, status: "offline", teams: "Maintenance", score: "—", meta: "Net inspection", action: "Details" },
];

export const courtOperationsSeed = [
  {
    id: "court-1",
    number: 1,
    name: "Court 1",
    zone: "Main Courts",
    status: "live",
    surface: "Artificial turf",
    surfaceCondition: "Excellent",
    lighting: "Good",
    environment: "Indoor",
    deviceStatus: "connected",
    displayStatus: "connected",
    deviceId: "PAD-SCR-001",
    displayId: "PAD-DSP-001",
    lastSync: "Just now",
    notes: "Championship court. Broadcast camera enabled.",
    currentMatch: {
      id: "match-4",
      tournament: "Challenger 2026",
      round: "Quarter Finals",
      matchNumber: "Match 4",
      teamA: "E / L",
      teamB: "S / H",
      scoreA: "30",
      scoreB: "15",
      setLabel: "Set 1",
      gameLabel: "Game 8",
      server: "E / L",
      durationMinutes: 57,
    },
    nextMatch: {
      teamA: "G / N",
      teamB: "S / S",
      time: "13:30",
      tournament: "Challenger 2026",
      checkedIn: true,
    },
  },
  {
    id: "court-2",
    number: 2,
    name: "Court 2",
    zone: "Main Courts",
    status: "live",
    surface: "Artificial turf",
    surfaceCondition: "Good",
    lighting: "Good",
    environment: "Indoor",
    deviceStatus: "connected",
    displayStatus: "connected",
    deviceId: "PAD-SCR-002",
    displayId: "PAD-DSP-002",
    lastSync: "8 seconds ago",
    notes: "North-side spectator seating open.",
    currentMatch: {
      id: "match-5",
      tournament: "Challenger 2026",
      round: "Quarter Finals",
      matchNumber: "Match 5",
      teamA: "G / N",
      teamB: "S / S",
      scoreA: "40",
      scoreB: "30",
      setLabel: "Set 1",
      gameLabel: "Game 6",
      server: "S / S",
      durationMinutes: 63,
    },
    nextMatch: {
      teamA: "A / B",
      teamB: "K / T",
      time: "14:15",
      tournament: "Challenger 2026",
      checkedIn: false,
    },
  },
  {
    id: "court-3",
    number: 3,
    name: "Court 3",
    zone: "Main Courts",
    status: "waiting",
    surface: "Artificial turf",
    surfaceCondition: "Good",
    lighting: "Good",
    environment: "Indoor",
    deviceStatus: "connected",
    displayStatus: "connected",
    deviceId: "PAD-SCR-003",
    displayId: "PAD-DSP-003",
    lastSync: "24 seconds ago",
    notes: "Both teams are in the player tunnel.",
    currentMatch: {
      id: "match-6",
      tournament: "Challenger 2026",
      round: "Quarter Finals",
      matchNumber: "Match 6",
      teamA: "L / J",
      teamB: "C / C",
      scoreA: "0",
      scoreB: "0",
      setLabel: "Starts in 12 min",
      gameLabel: "Players checked in",
      server: "To be decided",
      durationMinutes: 0,
    },
    nextMatch: {
      teamA: "T / R",
      teamB: "M / P",
      time: "14:45",
      tournament: "Challenger 2026",
      checkedIn: true,
    },
  },
  {
    id: "court-4",
    number: 4,
    name: "Court 4",
    zone: "Outdoor Courts",
    status: "delayed",
    surface: "Artificial turf",
    surfaceCondition: "Wet",
    lighting: "Good",
    environment: "Outdoor",
    deviceStatus: "connected",
    displayStatus: "connected",
    deviceId: "PAD-SCR-004",
    displayId: "PAD-DSP-004",
    lastSync: "1 minute ago",
    notes: "Ground staff monitoring surface drainage.",
    delay: {
      reason: "Rain",
      durationMinutes: 15,
      estimatedResume: "13:05",
    },
    currentMatch: {
      id: "match-7",
      tournament: "Challenger 2026",
      round: "Quarter Finals",
      matchNumber: "Match 7",
      teamA: "J / L",
      teamB: "F / M",
      scoreA: "15",
      scoreB: "15",
      setLabel: "Set 1",
      gameLabel: "Game 4",
      server: "F / M",
      durationMinutes: 38,
    },
    nextMatch: {
      teamA: "P / V",
      teamB: "D / R",
      time: "14:00",
      tournament: "Schools Cup 2026",
      checkedIn: false,
    },
  },
  {
    id: "court-5",
    number: 5,
    name: "Court 5",
    zone: "Outdoor Courts",
    status: "completed",
    surface: "Artificial turf",
    surfaceCondition: "Good",
    lighting: "Good",
    environment: "Outdoor",
    deviceStatus: "connected",
    displayStatus: "connected",
    deviceId: "PAD-SCR-005",
    displayId: "PAD-DSP-005",
    lastSync: "2 minutes ago",
    notes: "Final score awaiting official confirmation.",
    currentMatch: {
      id: "match-8",
      tournament: "Challenger 2026",
      round: "Round 1",
      matchNumber: "Match 8",
      teamA: "A / B",
      teamB: "K / T",
      scoreA: "6–4, 6–3",
      scoreB: "Final",
      setLabel: "Completed",
      gameLabel: "Awaiting confirmation",
      server: "—",
      durationMinutes: 71,
      winner: "A / B",
    },
    nextMatch: {
      teamA: "N / K",
      teamB: "W / H",
      time: "13:20",
      tournament: "Schools Cup 2026",
      checkedIn: true,
    },
  },
  {
    id: "court-6",
    number: 6,
    name: "Court 6",
    zone: "Outdoor Courts",
    status: "maintenance",
    surface: "Artificial turf",
    surfaceCondition: "Inspection complete",
    lighting: "Fault reported",
    environment: "Outdoor",
    deviceStatus: "connected",
    displayStatus: "offline",
    deviceId: "PAD-SCR-006",
    displayId: "PAD-DSP-006",
    lastSync: "6 minutes ago",
    notes: "Do not assign evening matches until lighting is cleared.",
    issue: {
      title: "Lighting fault",
      reportedAt: "12:18",
      expectedResolution: "14:30",
    },
    currentMatch: null,
    nextMatch: {
      teamA: "C / M",
      teamB: "J / P",
      time: "15:00",
      tournament: "Challenger 2026",
      checkedIn: false,
    },
  },
  {
    id: "court-7",
    number: 7,
    name: "Court 7",
    zone: "Outdoor Courts",
    status: "available",
    surface: "Artificial turf",
    surfaceCondition: "Good",
    lighting: "Good",
    environment: "Outdoor",
    deviceStatus: "connected",
    displayStatus: "connected",
    deviceId: "PAD-SCR-007",
    displayId: "PAD-DSP-007",
    lastSync: "15 seconds ago",
    notes: "Available for match reassignment.",
    currentMatch: null,
    nextMatch: {
      teamA: "R / S",
      teamB: "M / D",
      time: "13:00",
      tournament: "Schools Cup 2026",
      checkedIn: false,
    },
  },
  {
    id: "court-8",
    number: 8,
    name: "Court 8",
    zone: "Academy Courts",
    status: "warm-up",
    surface: "Artificial turf",
    surfaceCondition: "Excellent",
    lighting: "Good",
    environment: "Indoor",
    deviceStatus: "connected",
    displayStatus: "connected",
    deviceId: "PAD-SCR-008",
    displayId: "PAD-DSP-008",
    lastSync: "12 seconds ago",
    notes: "Warm-up ends in 4 minutes.",
    currentMatch: {
      id: "match-10",
      tournament: "Schools Cup 2026",
      round: "Group Stage",
      matchNumber: "Match 10",
      teamA: "T / R",
      teamB: "M / P",
      scoreA: "—",
      scoreB: "—",
      setLabel: "Warm-up",
      gameLabel: "4 minutes remaining",
      server: "To be decided",
      durationMinutes: 0,
    },
    nextMatch: {
      teamA: "L / K",
      teamB: "B / G",
      time: "13:45",
      tournament: "Schools Cup 2026",
      checkedIn: true,
    },
  },
  {
    id: "court-9",
    number: 9,
    name: "Court 9",
    zone: "Academy Courts",
    status: "offline",
    surface: "Artificial turf",
    surfaceCondition: "Good",
    lighting: "Good",
    environment: "Indoor",
    deviceStatus: "offline",
    displayStatus: "offline",
    deviceId: "PAD-SCR-009",
    displayId: "PAD-DSP-009",
    lastSync: "18 minutes ago",
    notes: "Scoring device disconnected from the club network.",
    currentMatch: null,
    nextMatch: {
      teamA: "S / P",
      teamB: "N / B",
      time: "13:25",
      tournament: "Schools Cup 2026",
      checkedIn: false,
    },
  },
  {
    id: "court-10",
    number: 10,
    name: "Court 10",
    zone: "Academy Courts",
    status: "available",
    surface: "Artificial turf",
    surfaceCondition: "Good",
    lighting: "Good",
    environment: "Indoor",
    deviceStatus: "connected",
    displayStatus: "connected",
    deviceId: "PAD-SCR-010",
    displayId: "PAD-DSP-010",
    lastSync: "19 seconds ago",
    notes: "Coaching equipment stored courtside.",
    currentMatch: null,
    nextMatch: {
      teamA: "F / A",
      teamB: "R / T",
      time: "13:40",
      tournament: "Schools Cup 2026",
      checkedIn: false,
    },
  },
];

const detailedMatches = [
  {
    id: "match-4",
    tournament: "Challenger 2026",
    round: "Quarter Final",
    court: "Court 1",
    status: "live",
    start: "11:30",
    date: "2026-07-28",
    duration: 57,
    format: "Best of 3",
    official: "Amelia Ross",
    teamA: { players: ["Ethan Meyer", "Liam Jacobs"], short: "E / L", seed: 1, club: "Hermanus Sports Club", server: true },
    teamB: { players: ["Sam Hart", "Hugo Naudé"], short: "S / H", seed: 8, club: "Cape Town Padel Park", server: false },
    score: { pointsA: "30", pointsB: "15", setsA: [6, 3], setsB: [4, 2], currentSet: 2 },
    history: [
      ["10:54", "Players checked in"],
      ["11:31", "Match started"],
      ["12:02", "Medical timeout · Team B"],
      ["12:07", "Play resumed"],
    ],
    notes: { tournament: "Winner progresses to Semi Final 1.", official: "Medical timeout resolved. No further treatment required.", incident: "Physio attended Court 1 at 12:02." },
  },
  {
    id: "match-5",
    tournament: "Challenger 2026",
    round: "Quarter Final",
    court: "Court 2",
    status: "live",
    start: "11:30",
    date: "2026-07-28",
    duration: 63,
    format: "Best of 3",
    official: "Noah Williams",
    teamA: { players: ["Grace Adams", "Nina Smith"], short: "G / N", seed: 3, club: "Overberg Padel Centre", server: false },
    teamB: { players: ["Sofia James", "Sarah Scott"], short: "S / S", seed: 6, club: "Hermanus Sports Club", server: true },
    score: { pointsA: "40", pointsB: "30", setsA: [4, 5], setsB: [6, 4], currentSet: 2 },
    history: [["10:58", "Players checked in"], ["11:34", "Match started"], ["12:20", "New balls issued"]],
    notes: { tournament: "Standard quarter-final rules.", official: "Match progressing normally.", incident: "No incidents." },
  },
  {
    id: "match-6",
    tournament: "Challenger 2026",
    round: "Quarter Final",
    court: "Court 3",
    status: "waiting",
    start: "12:45",
    date: "2026-07-28",
    duration: 0,
    format: "Best of 3",
    official: "Mia Daniels",
    teamA: { players: ["Luke Fourie", "Joshua King"], short: "L / J", seed: 4, club: "Hermanus Sports Club", server: true },
    teamB: { players: ["Connor Botha", "Caleb Visser"], short: "C / C", seed: 5, club: "Cape Town Padel Park", server: false },
    score: { pointsA: "0", pointsB: "0", setsA: [], setsB: [], currentSet: 1 },
    history: [["12:16", "Team A checked in"], ["12:19", "Team B checked in"], ["12:22", "Court assigned"]],
    notes: { tournament: "Start as soon as Court 3 is cleared.", official: "Both teams ready.", incident: "No incidents." },
  },
  {
    id: "match-7",
    tournament: "Challenger 2026",
    round: "Quarter Final",
    court: "Court 4",
    status: "delayed",
    start: "12:00",
    date: "2026-07-28",
    duration: 22,
    format: "Best of 3",
    official: "Leah Smith",
    teamA: { players: ["James Nel", "Leo Marais"], short: "J / L", seed: 2, club: "Stellenbosch Padel", server: false },
    teamB: { players: ["Finn Ross", "Mason Cole"], short: "F / M", seed: 7, club: "Overberg Padel Centre", server: true },
    score: { pointsA: "15", pointsB: "15", setsA: [2], setsB: [2], currentSet: 1 },
    history: [["11:42", "Players checked in"], ["12:01", "Match started"], ["12:23", "Rain delay started"]],
    notes: { tournament: "Weather protocol active.", official: "Court surface inspection due at 12:45.", incident: "Rain delay; players moved indoors." },
  },
  {
    id: "match-8",
    tournament: "Schools Cup 2026",
    round: "Group A",
    court: "Court 7",
    status: "warm-up",
    start: "13:00",
    date: "2026-07-28",
    duration: 4,
    format: "Best of 3",
    official: "Tyler Brown",
    teamA: { players: ["Ryan Day", "Sam Nel"], short: "R / S", seed: 2, club: "Hermanus High", server: true },
    teamB: { players: ["Mika Ross", "Daniel Lee"], short: "M / D", seed: 5, club: "Parel Vallei High", server: false },
    score: { pointsA: "0", pointsB: "0", setsA: [], setsB: [], currentSet: 1 },
    history: [["12:35", "Players checked in"], ["12:52", "Warm-up started"]],
    notes: { tournament: "Group-stage match.", official: "Warm-up ends at 13:00.", incident: "No incidents." },
  },
  {
    id: "match-9",
    tournament: "Schools Cup 2026",
    round: "Group B",
    court: "Court 8",
    status: "scheduled",
    start: "13:30",
    date: "2026-07-28",
    duration: 0,
    format: "Best of 3",
    official: "Unassigned",
    teamA: { players: ["Nora King", "Kara West"], short: "N / K", seed: 1, club: "Rhenish Girls' High", server: false },
    teamB: { players: ["Will Hart", "Henk Botha"], short: "W / H", seed: 4, club: "Paul Roos Gymnasium", server: true },
    score: { pointsA: "0", pointsB: "0", setsA: [], setsB: [], currentSet: 1 },
    history: [["09:12", "Match scheduled"], ["12:40", "Team A checked in"]],
    notes: { tournament: "Awaiting Team B check-in.", official: "Official assignment pending.", incident: "No incidents." },
  },
  {
    id: "match-10",
    tournament: "Club Championships",
    round: "Round 1",
    court: "Court 5",
    status: "paused",
    start: "10:30",
    date: "2026-07-28",
    duration: 41,
    format: "Best of 3",
    official: "Daniel Kruger",
    teamA: { players: ["Ava Smith", "Emma Ross"], short: "A / E", seed: 5, club: "Hermanus Sports Club", server: true },
    teamB: { players: ["Lily Nel", "Olivia Hart"], short: "L / O", seed: 12, club: "Hermanus Sports Club", server: false },
    score: { pointsA: "40", pointsB: "40", setsA: [6, 1], setsB: [3, 2], currentSet: 2 },
    history: [["10:07", "Players checked in"], ["10:31", "Match started"], ["11:12", "Equipment pause"]],
    notes: { tournament: "Club ranking points apply.", official: "Replacement racket requested.", incident: "Team B racket damaged." },
  },
  {
    id: "match-11",
    tournament: "Club Championships",
    round: "Round 1",
    court: "Court 6",
    status: "review",
    start: "09:00",
    date: "2026-07-28",
    duration: 76,
    format: "Best of 3",
    official: "Amelia Ross",
    teamA: { players: ["Tom Meyer", "Ian Cole"], short: "T / I", seed: 4, club: "Hermanus Sports Club", server: false },
    teamB: { players: ["Paul Dean", "Adam King"], short: "P / A", seed: 13, club: "Hermanus Sports Club", server: true },
    score: { pointsA: "FINAL", pointsB: "", setsA: [6, 4, 7], setsB: [3, 6, 6], currentSet: 3 },
    history: [["08:34", "Players checked in"], ["09:02", "Match started"], ["10:18", "Result submitted"], ["10:20", "Flagged for review"]],
    notes: { tournament: "Verify final-set tiebreak.", official: "Winning score submitted as 7–6.", incident: "Result confirmation required." },
  },
  {
    id: "match-12",
    tournament: "Winter League",
    round: "Round Robin 1",
    court: "Court 10",
    status: "completed",
    start: "09:00",
    date: "2026-07-28",
    duration: 68,
    format: "Best of 3",
    official: "Mia Daniels",
    teamA: { players: ["Ben Ross", "Kyle Smith"], short: "B / K", seed: 2, club: "Overberg Padel Centre", server: false },
    teamB: { players: ["Chad Lee", "Neil Day"], short: "C / N", seed: 7, club: "Cape Town Padel Park", server: true },
    score: { pointsA: "WIN", pointsB: "", setsA: [6, 6], setsB: [4, 2], currentSet: 2 },
    history: [["08:31", "Players checked in"], ["09:00", "Match started"], ["10:08", "Result confirmed"]],
    notes: { tournament: "League result published.", official: "Result verified.", incident: "No incidents." },
  },
  {
    id: "match-13",
    tournament: "Challenger 2026",
    round: "Semi Final",
    court: "TBC",
    status: "scheduled",
    start: "15:00",
    date: "2026-07-28",
    duration: 0,
    format: "Best of 3",
    official: "Noah Williams",
    teamA: { players: ["Winner QF1"], short: "QF1", seed: 0, club: "TBC", server: false },
    teamB: { players: ["Winner QF2"], short: "QF2", seed: 0, club: "TBC", server: false },
    score: { pointsA: "0", pointsB: "0", setsA: [], setsB: [], currentSet: 1 },
    history: [["08:00", "Match generated"]],
    notes: { tournament: "Court assigned after quarter finals.", official: "Briefing at 14:45.", incident: "No incidents." },
  },
  {
    id: "match-14",
    tournament: "Challenger 2026",
    round: "Semi Final",
    court: "TBC",
    status: "scheduled",
    start: "15:00",
    date: "2026-07-28",
    duration: 0,
    format: "Best of 3",
    official: "Leah Smith",
    teamA: { players: ["Winner QF3"], short: "QF3", seed: 0, club: "TBC", server: false },
    teamB: { players: ["Winner QF4"], short: "QF4", seed: 0, club: "TBC", server: false },
    score: { pointsA: "0", pointsB: "0", setsA: [], setsB: [], currentSet: 1 },
    history: [["08:00", "Match generated"]],
    notes: { tournament: "Court assigned after quarter finals.", official: "Briefing at 14:45.", incident: "No incidents." },
  },
  {
    id: "match-15",
    tournament: "Schools Cup 2026",
    round: "Group A",
    court: "Court 9",
    status: "cancelled",
    start: "10:00",
    date: "2026-07-28",
    duration: 0,
    format: "Best of 3",
    official: "Tyler Brown",
    teamA: { players: ["Mia Nel", "Amy Day"], short: "M / A", seed: 3, club: "Hermanus High", server: false },
    teamB: { players: ["Zoe King", "Ella Hart"], short: "Z / E", seed: 6, club: "Parel Vallei High", server: false },
    score: { pointsA: "—", pointsB: "—", setsA: [], setsB: [], currentSet: 0 },
    history: [["09:05", "Team A checked in"], ["09:42", "Match cancelled"]],
    notes: { tournament: "Reschedule pending.", official: "Court device failure.", incident: "Cancelled due to unavailable court." },
  },
];

const generatedStatuses = ["completed", "completed", "completed", "waiting", "scheduled", "completed", "waiting", "completed", "scheduled", "completed", "completed", "waiting", "scheduled", "completed", "walkover", "completed", "retired", "scheduled", "completed", "completed"];
const generatedTournaments = ["Challenger 2026", "Schools Cup 2026", "Club Championships", "Winter League"];
const generatedRounds = ["Round 1", "Group A", "Round Robin 1", "Round 2"];
const generatedTimes = ["09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30"];
const generatedInitials = ["R / T", "N / B", "F / A", "D / W", "K / P", "J / C", "V / M", "H / S"];

export const matchOperationsSeed = [
  ...detailedMatches,
  ...generatedStatuses.map((status, index) => {
    const complete = ["completed", "walkover", "retired"].includes(status);
    const teamA = generatedInitials[index % generatedInitials.length];
    const teamB = generatedInitials[(index + 3) % generatedInitials.length];
    return {
      id: `match-${index + 16}`,
      tournament: generatedTournaments[index % generatedTournaments.length],
      round: generatedRounds[index % generatedRounds.length],
      court: `Court ${(index % 10) + 1}`,
      status,
      start: generatedTimes[index],
      date: "2026-07-28",
      duration: complete ? 48 + (index % 5) * 7 : 0,
      format: index % 3 === 0 ? "Single set" : "Best of 3",
      official: index % 4 === 0 ? "Unassigned" : ["Amelia Ross", "Noah Williams", "Mia Daniels"][index % 3],
      teamA: { players: [`Player ${index * 4 + 1}`, `Player ${index * 4 + 2}`], short: teamA, seed: (index % 8) + 1, club: "Hermanus Sports Club", server: !complete },
      teamB: { players: [`Player ${index * 4 + 3}`, `Player ${index * 4 + 4}`], short: teamB, seed: ((index + 3) % 8) + 1, club: "Cape Town Padel Park", server: false },
      score: complete
        ? { pointsA: "WIN", pointsB: "", setsA: [6, 6], setsB: [3 + (index % 2), 2 + (index % 3)], currentSet: 2 }
        : { pointsA: "0", pointsB: "0", setsA: [], setsB: [], currentSet: 1 },
      history: [["08:00", "Match generated"], ...(complete ? [[generatedTimes[index], "Result confirmed"]] : [])],
      notes: { tournament: "Tournament schedule match.", official: complete ? "Result verified." : "Pre-match checks pending.", incident: "No incidents." },
    };
  }),
];

const featuredPlayers = [
  { id: "player-jakkie-swart", firstName: "Jakkie", lastName: "Swart", displayName: "Jakkie Swart", initials: "JS", email: "jakkie@example.com", mobile: "+27 82 410 7721", club: "Hermanus Sports Club", level: 4.52, preferredSide: "Left", dominantHand: "Right", status: "active", matches: 284, wins: 202, losses: 82, winRate: 71, currentStreak: 8, ranking: 12, currentTeam: "J / L", regularPartner: "Louis Botha", coach: "Mia Daniels", averageDuration: 64, recentForm: ["W", "W", "L", "W", "W"], notes: "Strong tactical awareness on the left side.", participation: "4 competitions" },
  { id: "player-louis-botha", firstName: "Louis", lastName: "Botha", displayName: "Louis Botha", initials: "LB", email: "louis@example.com", mobile: "+27 82 550 3842", club: "Hermanus Sports Club", level: 4.36, preferredSide: "Right", dominantHand: "Right", status: "active", matches: 241, wins: 164, losses: 77, winRate: 68, currentStreak: 5, ranking: 18, currentTeam: "J / L", regularPartner: "Jakkie Swart", coach: "Mia Daniels", averageDuration: 61, recentForm: ["W", "L", "W", "W", "W"], notes: "Reliable right-side defender and transition player.", participation: "4 competitions" },
  { id: "player-emma-lewis", firstName: "Emma", lastName: "Lewis", displayName: "Emma Lewis", initials: "EL", email: "emma@example.com", mobile: "+27 82 705 1123", club: "Overstrand Padel Club", level: 4.74, preferredSide: "Right", dominantHand: "Right", status: "active", matches: 193, wins: 147, losses: 46, winRate: 76, currentStreak: 11, ranking: 6, currentTeam: "E / L", regularPartner: "Leo Jacobs", coach: "Carla van Wyk", averageDuration: 58, recentForm: ["W", "W", "W", "L", "W"], notes: "High-tempo competitor with an aggressive return game.", participation: "3 competitions" },
  { id: "player-sophie-hart", firstName: "Sophie", lastName: "Hart", displayName: "Sophie Hart", initials: "SH", email: "sophie@example.com", mobile: "+27 71 880 4520", club: "Schools Cup Academy", level: 3.82, preferredSide: "Left", dominantHand: "Right", status: "active", matches: 96, wins: 57, losses: 39, winRate: 59, currentStreak: 2, ranking: 44, currentTeam: "S / H", regularPartner: "Hannah Smith", coach: "Theo Jacobs", averageDuration: 55, recentForm: ["L", "W", "W", "L", "W"], notes: "Junior pathway player developing overhead consistency.", participation: "2 competitions" },
  { id: "player-marco-ferreira", firstName: "Marco", lastName: "Ferreira", displayName: "Marco Ferreira", initials: "MF", email: "marco@example.com", mobile: "+27 83 336 9041", club: "Hermanus Sports Club", level: 4.11, preferredSide: "Right", dominantHand: "Left", status: "incomplete", matches: 117, wins: 75, losses: 42, winRate: 64, currentStreak: 3, ranking: 29, currentTeam: "F / M", regularPartner: "Finn Ross", coach: "Unassigned", averageDuration: 66, recentForm: ["W", "L", "W", "W", "L"], notes: "Emergency contact and profile image still required.", participation: "2 competitions" },
];

const generatedPlayerNames = [
  ["Leo", "Jacobs"], ["Hannah", "Smith"], ["Mia", "Nel"], ["Ryan", "Day"], ["Nora", "King"],
  ["Caleb", "Visser"], ["Grace", "Adams"], ["Finn", "Ross"], ["Sara", "Cole"], ["Julia", "Dean"],
  ["Ethan", "Meyer"], ["Nina", "Scott"], ["David", "Hart"], ["Kara", "West"], ["Tom", "Naudé"],
];
const communityClubs = ["Hermanus Sports Club", "Overstrand Padel Club", "Schools Cup Academy", "Cape Town Padel Park"];

export const communityPlayersSeed = [
  ...featuredPlayers,
  ...generatedPlayerNames.map(([firstName, lastName], index) => {
    const matches = 42 + index * 9;
    const winRate = 52 + (index * 3) % 24;
    const status = index % 7 === 4 ? "incomplete" : index % 9 === 6 ? "invited" : index === 13 ? "inactive" : "active";
    return {
      id: `player-${firstName.toLowerCase()}-${lastName.toLowerCase().replace("é", "e")}`,
      firstName,
      lastName,
      displayName: `${firstName} ${lastName}`,
      initials: `${firstName[0]}${lastName[0]}`,
      email: `${firstName.toLowerCase()}.${lastName.toLowerCase()}@example.com`,
      mobile: `+27 82 000 ${String(1200 + index).padStart(4, "0")}`,
      club: communityClubs[index % communityClubs.length],
      level: Number((3.18 + (index % 8) * 0.21).toFixed(2)),
      preferredSide: index % 2 ? "Right" : "Left",
      dominantHand: index % 5 === 0 ? "Left" : "Right",
      status,
      matches,
      wins: Math.round(matches * winRate / 100),
      losses: matches - Math.round(matches * winRate / 100),
      winRate,
      currentStreak: 1 + index % 6,
      ranking: 21 + index * 3,
      currentTeam: index % 5 === 3 ? "Unassigned" : `${firstName[0]} / ${generatedPlayerNames[(index + 1) % generatedPlayerNames.length][0][0]}`,
      regularPartner: generatedPlayerNames[(index + 1) % generatedPlayerNames.length].join(" "),
      coach: ["Mia Daniels", "Theo Jacobs", "Carla van Wyk", "Unassigned"][index % 4],
      averageDuration: 51 + index % 17,
      recentForm: index % 2 ? ["W", "L", "W", "W", "L"] : ["L", "W", "W", "L", "W"],
      notes: status === "incomplete" ? "Competition profile needs additional information." : "Community profile reviewed this month.",
      participation: `${1 + index % 4} competitions`,
    };
  }),
];

export const communityTeamsSeed = [
  { id: "team-j-l", name: "J / L", playerNames: ["Jakkie Swart", "Louis Botha"], club: "Hermanus Sports Club", seed: 4, group: "Quarter Finals", status: "active", matches: 42, wins: 29, losses: 13, winRate: 69, competitions: ["Challenger 2026"], ranking: 8, duration: "14 months", formation: "Left / Right", notes: "Established partnership with strong transition play.", recentResults: ["W 6–4, 6–3", "W 7–6, 6–4", "L 4–6, 3–6"] },
  { id: "team-e-l", name: "E / L", playerNames: ["Emma Lewis", "Leo Jacobs"], club: "Overstrand Padel Club", seed: 1, group: "Quarter Finals", status: "active", matches: 38, wins: 29, losses: 9, winRate: 76, competitions: ["Challenger 2026", "Winter League"], ranking: 2, duration: "11 months", formation: "Right / Left", notes: "Top seed with the highest current win rate.", recentResults: ["W 6–2, 6–3", "W 6–4, 7–5", "W 6–1, 6–2"] },
  { id: "team-s-h", name: "S / H", playerNames: ["Sophie Hart", "Hannah Smith"], club: "Schools Cup Academy", seed: 8, group: "Group A", status: "active", matches: 14, wins: 8, losses: 6, winRate: 57, competitions: ["Schools Cup 2026"], ranking: 31, duration: "5 months", formation: "Left / Right", notes: "Junior development pairing.", recentResults: ["W 6–4, 6–4", "L 3–6, 5–7", "W 7–5, 6–2"] },
  ...["F / M", "G / N", "R / T", "N / B", "K / P", "D / W", "C / J", "A / E", "V / S"].map((name, index) => ({
    id: `team-${name.toLowerCase().replaceAll(" ", "").replace("/", "-")}`,
    name,
    playerNames: [communityPlayersSeed[(index + 4) % communityPlayersSeed.length].displayName, communityPlayersSeed[(index + 7) % communityPlayersSeed.length].displayName],
    club: communityClubs[index % communityClubs.length],
    seed: index + 2,
    group: index % 2 ? "Group B" : "Round 1",
    status: index === 5 ? "draft" : index === 7 ? "pending invitation" : "active",
    matches: 12 + index * 3,
    wins: 7 + index * 2,
    losses: 5 + index,
    winRate: 55 + index * 2,
    competitions: [index % 2 ? "Schools Cup 2026" : "Club Championships"],
    ranking: 14 + index * 4,
    duration: `${3 + index} months`,
    formation: index % 2 ? "Right / Left" : "Left / Right",
    notes: "Competition pairing profile.",
    recentResults: ["W 6–4, 6–3", "L 4–6, 6–7", "W 6–2, 6–4"],
  })),
];

export const communityCoachesSeed = [
  { id: "coach-mia-daniels", displayName: "Mia Daniels", initials: "MD", email: "mia@padeuce.co.za", mobile: "+27 82 441 2030", club: "Hermanus Sports Club", speciality: "Tactical", status: "available", playersAssigned: 8, teamsAssigned: 3, certification: "Padel SA Level 3", contactStatus: "Verified", upcoming: ["Today · 15:30 · Jakkie Swart", "Thu · 09:00 · J / L"], notes: "Tournament preparation focus." },
  { id: "coach-theo-jacobs", displayName: "Theo Jacobs", initials: "TJ", email: "theo@academy.co.za", mobile: "+27 83 901 4421", club: "Schools Cup Academy", speciality: "Junior Development", status: "assigned", playersAssigned: 14, teamsAssigned: 5, certification: "Youth Development L2", contactStatus: "Verified", upcoming: ["Wed · 14:00 · Schools squad", "Fri · 15:00 · S / H"], notes: "Leads junior pathway programme." },
  { id: "coach-carla-van-wyk", displayName: "Carla van Wyk", initials: "CV", email: "carla@overstrand.co.za", mobile: "+27 71 405 1190", club: "Overstrand Padel Club", speciality: "Fitness", status: "available", playersAssigned: 6, teamsAssigned: 2, certification: "Sports Conditioning L3", contactStatus: "Verified", upcoming: ["Thu · 07:30 · Emma Lewis"], notes: "Return-to-play and conditioning." },
  { id: "coach-ben-malan", displayName: "Ben Malan", initials: "BM", email: "ben@ctpadel.co.za", mobile: "+27 82 334 0901", club: "Cape Town Padel Park", speciality: "Technical", status: "unavailable", playersAssigned: 5, teamsAssigned: 1, certification: "Padel SA Level 2", contactStatus: "Verified", upcoming: ["Mon · 10:00 · Technique clinic"], notes: "Unavailable until 3 August." },
  { id: "coach-lara-smith", displayName: "Lara Smith", initials: "LS", email: "lara@example.com", mobile: "+27 82 740 3341", club: "Hermanus Sports Club", speciality: "Tournament Preparation", status: "pending approval", playersAssigned: 0, teamsAssigned: 0, certification: "Application pending", contactStatus: "Invited", upcoming: [], notes: "Certification documents under review." },
];

export const communityOfficialsSeed = [
  { id: "official-sarah-miller", displayName: "Sarah Miller", initials: "SM", email: "sarah@padeuce.co.za", mobile: "+27 82 770 4431", club: "Padel South Africa", role: "Referee", certification: "Level 2 certification", status: "available", assignedCourt: "Court 3", assignedMatch: "Match 8", nextAssignment: "Court 5 · 14:30", availability: "Available after 14:30", contactStatus: "Verified", conflicts: 0, incidents: ["Medical timeout · Court 3 · Resolved"], notes: "Quarter-final referee rotation." },
  { id: "official-daniel-kruger", displayName: "Daniel Kruger", initials: "DK", email: "daniel@padeuce.co.za", mobile: "+27 82 331 9008", club: "Hermanus Sports Club", role: "Tournament Director", certification: "National Director", status: "assigned", assignedCourt: "Operations", assignedMatch: "Challenger 2026", nextAssignment: "Prize giving · 20:00", availability: "On duty", contactStatus: "Verified", conflicts: 1, incidents: ["Schedule conflict · 15:00 · Open"], notes: "Primary event escalation contact." },
  { id: "official-leah-smith", displayName: "Leah Smith", initials: "LS", email: "leah@padeuce.co.za", mobile: "+27 71 404 5581", club: "Padel South Africa", role: "Score Verifier", certification: "Score verification L2", status: "assigned", assignedCourt: "Court 4", assignedMatch: "Match 7", nextAssignment: "Match 14 · 15:00", availability: "Assigned until 13:30", contactStatus: "Verified", conflicts: 1, incidents: ["Rain delay log · Court 4"], notes: "Review pending result before next assignment." },
  { id: "official-tyler-brown", displayName: "Tyler Brown", initials: "TB", email: "tyler@example.com", mobile: "+27 83 251 6840", club: "Schools Cup Academy", role: "Court Marshal", certification: "Club official L1", status: "available", assignedCourt: "Court 7", assignedMatch: "Match 8", nextAssignment: "Court 8 · 15:30", availability: "Available after 14:00", contactStatus: "Verified", conflicts: 0, incidents: [], notes: "Schools Cup court rotation." },
  { id: "official-amelia-ross", displayName: "Amelia Ross", initials: "AR", email: "amelia@padeuce.co.za", mobile: "+27 82 112 5709", club: "Padel South Africa", role: "Referee", certification: "Level 3 certification", status: "assigned", assignedCourt: "Court 1", assignedMatch: "Match 4", nextAssignment: "Semi Final 1 · 15:00", availability: "Assigned", contactStatus: "Verified", conflicts: 1, incidents: ["Medical timeout · Match 4 · Resolved"], notes: "Senior referee for finals programme." },
  { id: "official-nadine-lee", displayName: "Nadine Lee", initials: "NL", email: "nadine@example.com", mobile: "+27 82 109 2280", club: "Overberg Medical Response", role: "Medical Official", certification: "Advanced life support", status: "pending approval", assignedCourt: "Medical station", assignedMatch: "Unassigned", nextAssignment: "On-call · 16:00", availability: "Pending approval", contactStatus: "Invited", conflicts: 0, incidents: [], notes: "Credential review in progress." },
];

export const communityInvitationsSeed = [
  { id: "invite-1", recipient: "Nadine Lee", type: "Confirm official role", status: "pending", sentAt: "Today · 09:15" },
  { id: "invite-2", recipient: "Lara Smith", type: "Join Padeuce", status: "pending", sentAt: "Yesterday · 14:10" },
  { id: "invite-3", recipient: "David Hart", type: "Complete profile", status: "pending", sentAt: "26 Jul · 11:40" },
  { id: "invite-4", recipient: "Nina Scott", type: "Join team", status: "pending", sentAt: "25 Jul · 08:20" },
];

export const activities = [
  { icon: "●", title: "Court 1 · Match 6", detail: "Point scored by E / L", time: "Just now" },
  { icon: "✓", title: "Team G / N checked in", detail: "Quarter Final", time: "2 min" },
  { icon: "■", title: "Match 5 on Court 2 completed", detail: "S / S won 6–4, 6–3", time: "8 min" },
  { icon: "+", title: "Medical timeout · Court 3", detail: "Official notified", time: "14 min" },
  { icon: "↗", title: "New sponsor ad activated", detail: "Cape Coast Motors", time: "22 min" },
];

export const schedule = [
  { time: "09:00", title: "Round 1 started", status: "Complete" },
  { time: "11:30", title: "Quarter Finals", status: "In progress" },
  { time: "15:00", title: "Semi Finals", status: "Upcoming" },
  { time: "18:00", title: "Finals", status: "Upcoming" },
  { time: "20:00", title: "Prize Giving", status: "Upcoming" },
];

export const notifications = [
  { title: "Court 6 needs attention", time: "1 min ago", unread: true },
  { title: "Round 2 draw is ready", time: "8 min ago", unread: true },
  { title: "Sponsor campaign reached 10k views", time: "1 hour ago", unread: false },
];

export const navItems = [
  { route: "today", label: "Today", icon: "⌂" },
  { route: "competitions", label: "Competitions", icon: "◈" },
  { route: "courts", label: "Courts", icon: "▦" },
  { route: "matches", label: "Matches", icon: "◎" },
  { route: "community", label: "Community", icon: "◉" },
  { route: "insights", label: "Insights", icon: "↗" },
  { route: "sponsors", label: "Sponsors", icon: "◇" },
  { route: "assistant", label: "AI Assistant", icon: "✦", badge: "BETA" },
  { route: "administration", label: "Administration", icon: "⚙" },
];
