import { escapeCommunityMarkup } from "./community-utils.js";

export const personSteps = ["Role", "Details", "Club", "Competition Access", "Review"];

function roleChoice(role, current, icon) {
  return `<button class="${role === current ? "selected" : ""}" type="button" data-person-role="${role}"><span>${icon}</span><strong>${role}</strong><small>${role === current ? "Selected" : "Choose role"}</small></button>`;
}

function selectedOption(value, current) {
  return value === current ? " selected" : "";
}

function roleFields(draft) {
  if (draft.role === "Player") {
    return `<label>Level<input data-person-draft="level" type="number" min="1" max="7" step="0.01" value="${escapeCommunityMarkup(draft.level)}"></label><label>Preferred side<select data-person-draft="preferredSide"><option${selectedOption("Left", draft.preferredSide)}>Left</option><option${selectedOption("Right", draft.preferredSide)}>Right</option><option${selectedOption("Either", draft.preferredSide)}>Either</option></select></label><label>Dominant hand<select data-person-draft="dominantHand"><option${selectedOption("Right", draft.dominantHand)}>Right</option><option${selectedOption("Left", draft.dominantHand)}>Left</option></select></label>`;
  }
  if (draft.role === "Coach") {
    return `<label>Speciality<select data-person-draft="speciality"><option>Technical</option><option>Tactical</option><option>Fitness</option><option>Junior Development</option><option>Tournament Preparation</option></select></label><label>Certification<input data-person-draft="certification" value="${escapeCommunityMarkup(draft.certification)}"></label><label>Availability<select data-person-draft="availability"><option>Available</option><option>Assigned</option><option>Unavailable</option></select></label>`;
  }
  return `<label>Official role<select data-person-draft="officialRole"><option>Tournament Director</option><option>Referee</option><option>Court Marshal</option><option>Score Verifier</option><option>Medical Official</option></select></label><label>Certification<input data-person-draft="certification" value="${escapeCommunityMarkup(draft.certification)}"></label><label>Availability<select data-person-draft="availability"><option>Available</option><option>Assigned</option><option>Unavailable</option></select></label>`;
}

function personStepContent(step, draft) {
  if (step === 0) return `<div class="community-role-grid">${roleChoice("Player", draft.role, "◉")}${roleChoice("Coach", draft.role, "◎")}${roleChoice("Official", draft.role, "◇")}</div>`;
  if (step === 1) return `<div class="form-grid"><div class="profile-upload-placeholder"><span>${escapeCommunityMarkup((draft.firstName[0] || "") + (draft.lastName[0] || "") || "＋")}</span><button class="text-button" type="button" data-toast="Profile image selector opened">Add profile image</button></div><label>First name<input data-person-draft="firstName" value="${escapeCommunityMarkup(draft.firstName)}" required autofocus></label><label>Last name<input data-person-draft="lastName" value="${escapeCommunityMarkup(draft.lastName)}" required></label><label class="span-2">Display name<input data-person-draft="displayName" value="${escapeCommunityMarkup(draft.displayName)}"></label><label>Email<input data-person-draft="email" type="email" value="${escapeCommunityMarkup(draft.email)}" required></label><label>Mobile number<input data-person-draft="mobile" value="${escapeCommunityMarkup(draft.mobile)}"></label></div>`;
  if (step === 2) return `<div class="form-grid"><label class="span-2">Current club<select data-person-draft="club"><option>Hermanus Sports Club</option><option>Overstrand Padel Club</option><option>Schools Cup Academy</option><option>Cape Town Padel Park</option><option>Independent</option></select></label>${roleFields(draft)}</div>`;
  if (step === 3) return `<div class="community-access-list"><label><input type="checkbox" checked><span><strong>Club directory</strong><small>Visible to authorised club administrators.</small></span></label><label><input type="checkbox" checked><span><strong>Challenger 2026</strong><small>Participant or operational access.</small></span></label><label><input type="checkbox"><span><strong>Schools Cup 2026</strong><small>Optional competition access.</small></span></label><label><input type="checkbox" checked><span><strong>Live scoring notifications</strong><small>Receive relevant match updates.</small></span></label></div>`;
  return `<div class="community-review"><div><span>Role</span><strong>${escapeCommunityMarkup(draft.role)}</strong></div><div><span>Name</span><strong>${escapeCommunityMarkup(draft.displayName || `${draft.firstName} ${draft.lastName}`)}</strong></div><div><span>Email</span><strong>${escapeCommunityMarkup(draft.email || "Not supplied")}</strong></div><div><span>Club</span><strong>${escapeCommunityMarkup(draft.club)}</strong></div><div><span>Status</span><strong>Ready to add</strong></div></div>`;
}

export function addPersonWizardTemplate(step, draft) {
  return `<div class="community-wizard"><ol>${personSteps.map((label, index) => `<li class="${index === step ? "active" : index < step ? "complete" : ""}"><span>${index < step ? "✓" : index + 1}</span><b>${label}</b></li>`).join("")}</ol><p class="modal-step-title">Step ${step + 1} of 5 · ${personSteps[step]}</p><div class="community-wizard-content">${personStepContent(step, draft)}</div><div class="step-actions"><button class="button secondary" type="button" data-person-back>${step ? "Back" : "Cancel"}</button><div>${step === 4 ? '<button class="button ghost" type="button" data-person-save="draft">Save Draft</button>' : ""}<button class="button primary" type="button" data-person-next>${step === 4 ? "Add Person" : "Continue"} <span>→</span></button>${step === 4 ? '<button class="button secondary" type="button" data-person-save="invite">Add & Invite</button>' : ""}</div></div></div>`;
}

export function addTeamTemplate(players) {
  const options = players.map((player) => `<option value="${escapeCommunityMarkup(player.id)}">${escapeCommunityMarkup(player.displayName)}</option>`).join("");
  return `<form class="community-modal-form" data-community-form="add-team"><div class="form-grid"><label class="span-2">Team name<input name="name" placeholder="Generated from player initials"></label><label>Player 1<select name="player1" required>${options}</select></label><label>Player 2<select name="player2" required>${options}</select></label><label class="span-2">Club<select name="club"><option>Hermanus Sports Club</option><option>Overstrand Padel Club</option><option>Schools Cup Academy</option><option>Cape Town Padel Park</option></select></label><label>Seed<input name="seed" type="number" min="1" value="12"></label><label>Group<input name="group" value="Round 1"></label><label>Status<select name="status"><option value="active">Active</option><option value="draft">Draft</option><option value="pending invitation">Pending invitation</option></select></label><label class="span-2">Notes<textarea name="notes" rows="3"></textarea></label></div><p class="form-inline-error" data-team-error hidden>The same player cannot occupy both team positions.</p><div class="dialog-actions"><button class="button secondary" type="button" data-close-modal>Cancel</button><button class="button primary" type="submit">Add Team</button></div></form>`;
}

export function invitationTemplate(recipients, selectedId = "") {
  return `<form class="community-modal-form" data-community-form="invitation"><div class="form-grid"><label class="span-2">Recipient<select name="recipient">${recipients.map((item) => `<option value="${escapeCommunityMarkup(item.id)}"${item.id === selectedId ? " selected" : ""}>${escapeCommunityMarkup(item.displayName || item.name)}</option>`).join("")}</select></label><label>Invitation type<select name="type"><option>Join Padeuce</option><option>Complete profile</option><option>Join team</option><option>Enter tournament</option><option>Confirm official role</option></select></label><label>Tournament or club<select name="context"><option>Hermanus Sports Club</option><option>Challenger 2026</option><option>Schools Cup 2026</option></select></label><label class="span-2">Optional message<textarea name="message" rows="3" placeholder="Add a personal note…"></textarea></label><fieldset class="delivery-choice span-2"><legend>Delivery</legend><label><input name="delivery" type="radio" value="email" checked>Email</label><label><input name="delivery" type="radio" value="mobile">Mobile</label></fieldset></div><div class="dialog-actions"><button class="button secondary" type="button" data-close-modal>Cancel</button><button class="button primary" type="submit">Send Invitation</button></div></form>`;
}

export function communityImportTemplate() {
  return `<form class="community-modal-form" data-community-form="import"><div class="community-import-zone"><span>⇧</span><h3>Upload community CSV</h3><p>CSV or XLSX up to 10MB</p><label class="button secondary">Choose file<input name="file" type="file" accept=".csv,.xlsx" required></label></div><div class="form-grid"><label>Import type<select name="type"><option>Players</option><option>Teams</option><option>Coaches</option><option>Officials</option></select></label><div class="mapping-preview"><span>Field mapping</span><strong>Name → Display name</strong><small>Club → Club · Status → Status</small></div></div><div class="validation-summary"><span>✓</span><p><strong>Template ready</strong> Required fields and duplicate checks will be validated before import.</p></div><button class="text-button" type="button" data-toast="Community CSV template downloaded">Download CSV template →</button><div class="dialog-actions"><button class="button secondary" type="button" data-close-modal>Cancel</button><button class="button primary" type="submit">Import Records</button></div></form>`;
}

export function communityExportTemplate(activeTab) {
  return `<form class="community-modal-form" data-community-form="export"><p>Select the records to include in the CSV export.</p><div class="community-export-options"><label><input name="scope" type="radio" value="view" checked><span><strong>Export current view</strong><small>Uses the active ${escapeCommunityMarkup(activeTab)} filters.</small></span></label><label><input name="scope" type="radio" value="all"><span><strong>Export all community data</strong><small>Players, teams, coaches and officials.</small></span></label><label><input name="scope" type="radio" value="players"><span><strong>Export players only</strong><small>All player profiles and performance values.</small></span></label><label><input name="scope" type="radio" value="teams"><span><strong>Export teams only</strong><small>All partnerships and competition entries.</small></span></label></div><div class="dialog-actions"><button class="button secondary" type="button" data-close-modal>Cancel</button><button class="button primary" type="submit">Download CSV</button></div></form>`;
}
